# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import systeminfo_pb2 as systeminfo__pb2


class SysinfoStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetSysInfo = channel.unary_unary(
        '/Sysinfo/GetSysInfo',
        request_serializer=systeminfo__pb2.Sysstatus.SerializeToString,
        response_deserializer=systeminfo__pb2.Response.FromString,
        )
    self.GetProcesses = channel.stream_unary(
        '/Sysinfo/GetProcesses',
        request_serializer=systeminfo__pb2.Process.SerializeToString,
        response_deserializer=systeminfo__pb2.Response.FromString,
        )


class SysinfoServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetSysInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetProcesses(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SysinfoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetSysInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetSysInfo,
          request_deserializer=systeminfo__pb2.Sysstatus.FromString,
          response_serializer=systeminfo__pb2.Response.SerializeToString,
      ),
      'GetProcesses': grpc.stream_unary_rpc_method_handler(
          servicer.GetProcesses,
          request_deserializer=systeminfo__pb2.Process.FromString,
          response_serializer=systeminfo__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Sysinfo', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
